
export enum ActionTypes {
    GET_PROJECTS = 'GET_PROJECTS',
    GET_BIBTYPES = 'GET_BIBTYPES',
    GET_BIBENTRIES = 'GET_BIBENTRIES',
    CREATE_PROJECT = 'CREATE_PROJECT',
    DELETE_PROJECT = 'DELETE_PROJECT',
    SAVE_TYPE = 'SAVE_TYPE',
    SAVE_ENTRY = 'SAVE_ENTRY',
    DELETE_TYPE = 'DELETE_TYPE',
    DELETE_ENTRY = 'DELETE_ENTRY',
    BACKUP_PROJECT = 'BACKUP_PROJECT'
}