export enum MutationTypes {
    SET_PROJECT = 'SET_PROJECT',
    SET_PROJECTS = 'SET_PROJECTS',
    SET_BIBTYPES = 'SET_BIBTYPES',
    SET_BIBENTRIES = 'SET_BIBENTRIES',
    SET_TYPE_TO_EDIT = 'SET_TYPE_TO_EDIT',
    UPDATE_MODEL_FOR_TYPE = 'UPDATE_MODEL_FOR_TYPE',
    RM_BIB_ATTR = 'RM_BIB_ATTR',
    ADD_BIB_ATTR = 'ADD_BIB_ATTR'
}