export enum MutationTypes {
    SET_PROJECT = 'SET_PROJECT',
    SET_PROJECTS = 'SET_PROJECTS',
    SET_BIBTYPES = 'SET_BIBTYPES',
    SET_BIBENTRIES = 'SET_BIBENTRIES',
    UPDATE_MODEL_FOR_TYPE = 'UPDATE_MODEL_FOR_TYPE',
}