
export enum ActionTypes {
    APP_GET_PROJECTS = 'APP_GET_PROJECTS',
    APP_CREATE_PROJECT = 'APP_CREATE_PROJECT',
    PROJECT_DELETE_PROJECT = 'PROJECT_DELETE_PROJECT',
    PROJECT_BACKUP_PROJECT = 'PROJECT_BACKUP_PROJECT',
    PROJECT_GET_BACKUP_PATHS = 'PROJECT_GET_BACKUP_PATHS',
    PROJECT_RESET_TO_BACKUP = 'PROJECT_RESET_TO_BACKUP',
    PROJECT_GET_PROJECT_DATA = 'PROJECT_GET_PROJECT_DATA',
    EDITOR_SAVE_TYPE = 'EDITOR_SAVE_TYPE',
    EDITOR_DELETE_TYPE = 'EDITOR_DELETE_TYPE',
    EDITOR_SAVE_ENTRY = 'EDITOR_SAVE_ENTRY',
    EDITOR_DELETE_ENTRY = 'EDITOR_DELETE_ENTRY'
}