
export enum ActionTypes {
    APP_GET_PROJECTS = 'APP_GET_PROJECTS',
    APP_CREATE_PROJECT = 'APP_CREATE_PROJECT',
    PROJECT_DELETE_PROJECT = 'PROJECT_DELETE_PROJECT',
    PROJECT_BACKUP_PROJECT = 'BACKUP_PROJECT'
}