export enum MutationTypes {
    APP_SET_PROJECTNAMES = 'APP_SET_PROJECTNAMES',
    APP_SET_PROJECTNAME = 'APP_SET_PROJECTNAME',
    APP_SET_ERROR = 'APP_SET_ERROR',
    APP_SET_SUCCESS = 'APP_SET_SUCCESS',
    PROJECT_SET_BACKUP_PATHS = 'PROJECT_SET_BACKUP_PATHD',
    PROJECT_SET_PROJECT_DATA = 'PROJECT_SET_PROJECT_DATA',
    EDITOR_OPEN = 'EDITOR_OPEN'
}