export enum MutationTypes {
    APP_SET_PROJECTNAMES = 'APP_SET_PROJECTNAMES',
    APP_SET_PROJECTNAME = 'APP_SET_PROJECTNAME',
    APP_SET_ERROR = 'APP_SET_ERROR',
    APP_SET_SUCCESS = 'APP_SET_SUCCESS',
    APP_TOGGLE_TWO_THIRDS = 'APP_TOGGLE_TWO_THIRDS',
    PROJECT_SET_BACKUP_PATHS = 'PROJECT_SET_BACKUP_PATHD',
    PROJECT_SET_PROJECT_DATA = 'PROJECT_SET_PROJECT_DATA',
    EDITOR_OPEN = 'EDITOR_OPEN',
    PROJECT_UPDATE_TYPE_TO_EDIT = 'PROJECT_UPDATE_TYPE_TO_EDIT',
    PROJECT_UPDATE_ENTRY_TO_EDIT = 'PROJECT_UPDATE_ENTRY_TO_EDIT',
    EDITOR_SET_SAVELY_CLOSABLE = 'EDITOR_SET_SAVELY_CLOSABLE',
    PROJECT_RM_ENTRY = 'PROJECT_RM_ENTRY',
    PROJECT_RM_TYPE = 'PROJECT_RM_TYPE',
    PROJECT_SET_ABBRS = 'PROJECT_SET_ABBRS'
}