export enum MutationTypes {
    APP_SET_PROJECTNAMES = 'APP_SET_PROJECTNAMES',
    APP_SET_PROJECTNAME = 'APP_SET_PROJECTNAME',
    APP_SET_ERROR = 'APP_SET_ERROR',
    APP_SET_SUCCESS = 'APP_SET_SUCCESS'
}